CC=gcc
CFLAGS=-g -Wall -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26
LDFLAGS=-lfuse -lcrypto
SOURCE=lfs.c util.c inode.c container.c directory.c
OBJECTS=$(SOURCE:.c=.o)
EXECUTABLE=lfs

all:$(SOURCE) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)
.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<
clean:
	rm -rf *.o $(EXECUTABLE) lfslog

